version: '2'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:3.1.2
    environment:
      - "ZOOKEEPER_CLIENT_PORT=2181"
      - "ZOOKEEPER_TICK_TIME=2000"
      - "ZOOKEEPER_SYNC_LIMIT=2"
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:3.1.2
    environment:
      - "KAFKA_ZOOKEEPER_CONNECT=localhost:2181"
      - "KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092"
      - "KAFKA_BROKER_ID=1"
    ports:
      - "9092:9092"

  registry:
    image: confluentinc/cp-schema-registry:3.1.2
    environment:
      - "SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=localhost:2181"
      - "SCHEMA_REGISTRY_HOST_NAME=localhost"
      - "SCHEMA_REGISTRY_LISTENERS=http://localhost:8081"
      - "SCHEMA_REGISTRY_DEBUG=true"
    ports:
      - "8081:8081"

#  proxy:
#    image: confluentinc/cp-kafka-rest:3.1.2
#    environment:
#      - "KAFKA_REST_ZOOKEEPER_CONNECT=localhost:32181"
#      - "KAFKA_REST_LISTENERS=http://localhost:8082"
#      - "KAFKA_REST_SCHEMA_REGISTRY_URL=http://localhost:8081"
#    ports:
#      - "8082:8082"
#
#  connect:
#    image: confluentinc/cp-kafka-connect:3.1.2
#    environment:
#      - "CONNECT_BOOTSTRAP_SERVERS=localhost:29092"
#      - "CONNECT_REST_PORT=28082"
#      - "CONNECT_GROUP_ID=quickstart"
#      - "CONNECT_CONFIG_STORAGE_TOPIC=quickstart-config"
#      - "CONNECT_OFFSET_STORAGE_TOPIC=quickstart-offsets"
#      - "CONNECT_STATUS_STORAGE_TOPIC=quickstart-status"
#      - "CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter"
#      - "CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter"
#      - "CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter"
#      - "CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter"
#      - "CONNECT_REST_ADVERTISED_HOST_NAME=localhost"
#
#  control:
#    image: confluentinc/cp-control-center:3.1.2
#    environment:
#      - "CONTROL_CENTER_ZOOKEEPER_CONNECT=localhost:32181"
#      - "CONTROL_CENTER_BOOTSTRAP_SERVERS=localhost:29092"
#      - "CONTROL_CENTER_REPLICATION_FACTOR=1"
#      - "CONTROL_CENTER_CONNECT_CLUSTER=http://localhost:28082"
#
#  postgres:
#    image: postgres:9.5
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      - "POSTGRES_DB=postgres"
#      - "POSTGRES_USER=postgres"
#      - "POSTGRES_PASSWORD=postgres"
#    volumes:
#      - "./initdb:/docker-entrypoint-initdb.d"